# Generated by Django 3.1.3 on 2020-11-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booksLoans', '0001_initial'),
        ('ClientsLoans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loansTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateLoan', models.DateField()),
                ('dateReturn', models.DateField()),
                ('status', models.CharField(default='borrowed', max_length=10)),
                ('bookLoan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booksLoans.bookstable')),
                ('clientLoan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClientsLoans.clientstable')),
            ],
        ),
    ]
